import os
from colorama import Fore

def color_palette_generator(extractor, output_dir):
    """Generate color palette"""
    print(f"\n{Fore.BLUE}COLOR PALETTE GENERATOR")
    print("-" * 40)
    
    url = input(f"{Fore.YELLOW}Enter website URL: {Fore.WHITE}")
    if not url:
        return
    
    colors = extractor.extract_colors(url)
    if not colors:
        print(f"{Fore.RED}X No colors found!")
        return
    
    # Generate HTML palette
    html_content = generate_html_palette(colors, url)
    palette_file = os.path.join(output_dir, 'color_palette.html')
    with open(palette_file, 'w') as f:
        f.write(html_content)
    
    print(f"{Fore.GREEN}✓ Color palette saved to {palette_file}")
    input(f"\n{Fore.CYAN}Press Enter to continue...")

def generate_html_palette(colors, url):
    """Generate HTML color palette"""
    html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Color Palette - {url}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; }}
        .color-box {{ display: inline-block; width: 100px; height: 100px; margin: 10px; border: 1px solid #ccc; }}
        .color-info {{ text-align: center; margin-top: 5px; font-size: 12px; }}
    </style>
</head>
<body>
    <h1>Color Palette from {url}</h1>
    <p>Generated by CSS Color Extractor - Made by ACT91</p>
    <div>
"""
    for color in colors:
        if color.startswith('#') or color.startswith('rgb'):
            html += f'<div class="color-box" style="background-color: {color};"><div class="color-info">{color}</div></div>'
    
    html += """
    </div>
</body>
</html>"""
    return html