import os
from colorama import Fore

def export_html_swatches(extractor, output_dir):
    """Export color swatches as HTML"""
    print(f"\n{Fore.CYAN}EXPORT COLOR SWATCHES")
    print("-" * 40)
    
    url = input(f"{Fore.YELLOW}Enter website URL: {Fore.WHITE}")
    if not url:
        return
    
    colors = extractor.extract_colors(url)
    if not colors:
        print(f"{Fore.RED}X No colors found!")
        return
    
    html_content = generate_swatch_html(colors, url)
    filename = f"swatches_{url.replace('https://', '').replace('http://', '').replace('/', '_')}.html"
    filepath = os.path.join(output_dir, filename)
    
    with open(filepath, 'w') as f:
        f.write(html_content)
    
    print(f"{Fore.GREEN}✓ Color swatches exported to {filepath}")
    input(f"\n{Fore.CYAN}Press Enter to continue...")

def generate_swatch_html(colors, url):
    """Generate HTML color swatches"""
    html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Color Swatches - {url}</title>
    <style>
        body {{ font-family: 'Segoe UI', sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }}
        .header {{ text-align: center; margin-bottom: 30px; }}
        .swatch {{ display: inline-block; width: 120px; height: 120px; margin: 8px; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); position: relative; }}
        .swatch-label {{ position: absolute; bottom: -25px; left: 0; right: 0; text-align: center; font-size: 11px; color: #666; }}
        .grid {{ display: flex; flex-wrap: wrap; justify-content: center; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🎨 Color Swatches</h1>
        <p>Extracted from: <strong>{url}</strong></p>
        <p><em>Generated by CSS Color Extractor - Made by ACT91</em></p>
    </div>
    <div class="grid">
"""
    for color in colors:
        if color.startswith('#') or color.startswith('rgb'):
            html += f'<div class="swatch" style="background-color: {color};"><div class="swatch-label">{color}</div></div>'
    
    html += """
    </div>
</body>
</html>"""
    return html